### ISSUE TITLE
install term2 fail

### ISSUE THREAD

**Issue by chiisaihayashi** [webBoxio/atom-term2#100]
WIN7 64bit
ATOM v0.187.0

following error message is appeared.

Installing “term2@0.9.4” failed.Hide output…

> pty.js@0.2.6 install C:\Users\xxx\AppData\Local\Temp\apm-install-dir-115219-9032-upta0h\node_modules\term2\node_modules\pty.js
> node-gyp rebuild

C:\Users\xxx\AppData\Local\Temp\apm-install-dir-115219-9032-upta0h\node_modules\term2\node_modules\pty.js>node "C:\Users\xxx\AppData\Local\atom\app-0.187.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\xxx\\AppData\\Local\\atom\\app-0.187.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\xxx\\AppData\\Local\\atom\\app-0.187.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\xxx\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\xxx\\.atom\\.apmrc" "install" "C:\\Users\\xxx\\AppData\\Local\\Temp\\d-115219-9032-1490y43\\package.tgz" "--target=0.21.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by fogine** [comment]
I'm getting exactly same error when I try to install the package...

**Comment by imalitavakoli** [comment]
Also try installing the package manually, just download the zip file here and paste it into your 'package' directory:
`C:\Users\YOU\.atom\packages`

**Comment by bobrocke** [comment]
On Mac OS X 10.10 I get:

 pty.js@0.2.7-1 install /private/var/folders/r9/8p1xtdxj3qj6gf835pvd68sc0000gq/T/apm-install-dir-115417-75540-1dh7ryo/node_modules/term2/node_modules/pty.js
> node-gyp rebuild


make: *** No rule to make target `../../../../../../../../../../../../Users/bob/Dropbox/Application', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Development/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Applications/Development/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/r9/8p1xtdxj3qj6gf835pvd68sc0000gq/T/apm-install-dir-115417-75540-1dh7ryo/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "/Applications/Development/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Development/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/bob/Dropbox/Application Support/.atom/.apm/.apmrc" "--userconfig" "/Users/bob/Dropbox/Application Support/.atom/.apmrc" "install" "/private/var/folders/r9/8p1xtdxj3qj6gf835pvd68sc0000gq/T/d-115417-75540-15azdke/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/r9/8p1xtdxj3qj6gf835pvd68sc0000gq/T/apm-install-dir-115417-75540-1dh7ryo/npm-debug.log

**Comment by jaylinski** [comment]
same here, atom 1.0

**Comment by MoOx** [comment]
Dup of #132
