### ISSUE TITLE
terminal not working on atom version 0.187

### ISSUE THREAD

**Issue by veryluckyxyz** [webBoxio/atom-term2#101]
There is only blank screen (no prompt) when I click on Term2. It was working until recently.

Not sure if this has anything to do with the error but Atom's deprecation cop lists 5 deprecated calls: "atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace)"

and 1 deprecated selector Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by matthew-b-payne** [comment]
Also see this issue

**Comment by xasx** [comment]
I get this in the 'Incompatible Packages' pane:

```
Term2 0.9.4

Listed below are the incompatible native modules that this package depends on.

pty.js@0.2.4
Error message: Module version mismatch. Expected 41, got 16.
```

**Comment by sberan** [comment]
I have this issue too. Here is a screenshot of my console log when I open a terminal:

![image](https://cloud.githubusercontent.com/assets/100066/7572386/52948770-f7e3-11e4-94b1-f89e7b7e04c1.png)

**Comment by sberan** [comment]
update: uninstall and reinstall of term2 fixed this for me.

**Comment by MoOx** [comment]
I guess it's good now. Feel free to reopen an issue.
