### ISSUE TITLE
Focus issue when switching window pane from keyboard

### ISSUE THREAD

**Issue by MoOx** [webBoxio/atom-term2#108]
Hi,

First of all, thanks for this awesome plugin.
My problem is pretty quick to explain: when I move between pane using `window:focus-previous-pane` (or `window:focus-next-pane`), the tab totally focus (color change, etc) but I am not able to type in the console, I have to get focus with my mouse each time. Not sure why.
Any idea how can I fix that ?

I take a quick look to the code and see that it's supposed to work right ? https://github.com/webBoxio/atom-term2/blob/87d315461cb81f45a1f62218f7c6b75be5c1b81b/lib/TermView.coffee#L118-L125

**Comment by Nyalab** [comment]
:+1:, same issue here

**Comment by MoOx** [comment]
Please tell us if it's a kind of limitation.

**Comment by MoOx** [comment]
It's really annoying and I would like to fix this issue. Can any maintainer give me a clue about how to handle this issue ? I tried things for 5min without any success :(
(I barely can't read coffee :p)

**Comment by fbob** [comment]
:+1:  same issue here
fixing this issue will allow us to enjoy even more this this amazing plugin :)
Thanks

**Comment by bojidar-bg** [comment]
Maybe if https://github.com/webBoxio/atom-term2/blob/master/lib/TermView.coffee#L131 goes one line up... (not sure if it will work, just thinking)

**Comment by blaseva** [comment]
:+1:

**Comment by bgreen-litl** [comment]
:+1: It's actually racy for me. Sometimes the tab gets focus and sometimes it loses it and I need to click with mouse.

**Comment by MoOx** [comment]
I tried some stuff and it seems that we should start from here https://github.com/webBoxio/atom-term2/blob/master/index.coffee#L138
That's where the global term click is catched and where a variable is assigned, so looks like something is delayed and should not. Can someone help us on that ? At least a clue ?
Do owners of this repo even use this package? Otherwise I will create a fork because I see too many issue unanwsered. I understand that "PR or stfu" works most of the time, but this package is a bit more complicated so any pointers would be cool...
There is no tests at all so hard to know what you will break when making a PR... :/

**Comment by bojidar-bg** [comment]
YAY, now waiting for my atom to update the plugin :smile:

**Comment by MoOx** [comment]
The behavior using the keyboard only is not totally fixed right now, only the double click issue. Please subscribe to #6 for keyboard nav.

**Comment by Decoherence** [comment]
Potential workaround: 

⌘+KN to move the cursor to term2, then <tab> to activate the focus.
