### ISSUE TITLE
Resize the terminal

### ISSUE THREAD

**Issue by IngwiePhoenix** [webBoxio/atom-term2#114]
Is there a way to resize this thing? Its taking up 50% of the view and that is more than I need... o.o

**Comment by MoOx** [comment]
You need to use a plugin to be able to resize panes like this https://atom.io/packages/layout-manager

**Comment by IngwiePhoenix** [comment]
Figured. I am having this installed and I realized that it is the only solution fo many of the panel related modules. Thanks for your reply! :)
