### ISSUE TITLE
Switch tab while inside terminal

### ISSUE THREAD

**Issue by IngwiePhoenix** [webBoxio/atom-term2#115]
I just noticed that I can not switch between tabs while in the terminal using keystrokes. ctrl+tab does not work and I am not aware of any other to change tabs. The terminal seems to swallow every and all keystrokes that it obtains.

**Comment by MoOx** [comment]
Indeed. I am guessing the author(s) of this plugin are not using it all the times like some of us are.
@webBoxio/owners are you open to open this package to new contributors ?

**Comment by MoOx** [comment]
poke @vigo @f @tjmehta

**Comment by vigo** [comment]
yes we are very open for help! please help us out to fix this. fork/pr and i'll merge + release asap. lets fix this all together!

**Comment by MoOx** [comment]
Good to know ! Thanks for the fast reply :)
I try when I get some times to fix some issues that annoy me :)

**Comment by vigo** [comment]
that would be super kool @MoOx

**Comment by iamstarkov** [comment]
any news here?

**Comment by MoOx** [comment]
Duplicate of #6
