### ISSUE TITLE
cannot enable

### ISSUE THREAD

**Issue by chrisnesbit1** [webBoxio/atom-term2#119]
Even though the package is installed I don't see it under Settings > Packges. Yet when I go to Install > Packages it looks like it's installed but disabled. When I click enable it looks like nothing happens. Here's some screenshots of my developer tools when I open atom and when I try to enable term2.

![image](https://cloud.githubusercontent.com/assets/5253445/7515249/6ec12064-f493-11e4-8346-74217f390ed7.png)
![image](https://cloud.githubusercontent.com/assets/5253445/7515266/94ca483a-f493-11e4-8d8f-85922e164eb9.png)

p.s. I'm on a Macbook.

Thanks!
Chris

**Comment by MoOx** [comment]
What happen when you install it from CLI using `apm install term2` ?

**Comment by chrisnesbit1** [comment]
@MoOx hmm... it works.
