### ISSUE TITLE
Broken pane navigation

### ISSUE THREAD

**Issue by tompark-IO** [webBoxio/atom-term2#12]
This is similar to #6 but in this case when you navigate between panes using hotkeys the terminal doesn't capture the keyboard so you have to click twice inside the terminal pane to begin typing. It would be awesome if I could jump in and out with hotkeys.

Thanks keep up the good work!

**Comment by linusnorton** [comment]
Are there any workarounds for this?

**Comment by MoOx** [comment]
I guess it's the same as #6, closing for now.
