### ISSUE TITLE
Bottom panel terminal does not work!

### ISSUE THREAD

**Issue by fungl164** [webBoxio/atom-term2#126]
Thanks for your awesome plugin!

I have this on my styles.css: `.term2 .terminal {
   font-size: 11px;
}`

Whenever I open a terminal window on the lower panel of a split view the plugin does not display properly (see image below) and as soon as it loses focus the terminal becomes unusable.  Any way to fix this?  Thnxs!

![screen shot 2015-05-21 at 11 35 15 am](https://cloud.githubusercontent.com/assets/1827730/7752444/7cbd6324-ffad-11e4-8736-4507e9113aa6.png)

**Comment by MoOx** [comment]
We will improve custom still support, closing, please subscribe to #121
