### ISSUE TITLE
some apps not working inside term2 on OSX

### ISSUE THREAD

**Issue by liamcardenas** [webBoxio/atom-term2#135]
I followed the fix on issue #45 to get the path working, so I can use command line applications such as yeoman, however, for example, when I use yeoman inside term2, I get this:

```
yo react-webpack
? ==========================================================================
We're constantly looking for ways to make yo better!
May we anonymously report usage statistics to improve the tool over time?
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== Yes
Error react-webpack

You don't seem to have a generator with the name react-webpack installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.
$ React > generator-react-webpack
bash: generator-react-webpack: command not found
```

however, when I run the same command in terminal.app, it works (because generator-react-webpack is indeed installed). I don't want to make this issue about yeoman-- that's just an example. I am simply identifying this discrepancy in the behavior and wondering if there are any know fixes for this issue?

**Comment by MoOx** [comment]
It seems to be a PATH issue. Do you get different result when you type `echo $PATH` ?

**Comment by MoOx** [comment]
Dup of #50
