### ISSUE TITLE
Splitting left or right changes line-height

### ISSUE THREAD

**Issue by kjbrum** [webBoxio/atom-term2#142]
When I try to split a window right or left, the line-height for my terminal windows gets all messed up (http://dsh.re/8f28d). Works fine if I only split up or down.

**Comment by MoOx** [comment]
Can you confirm that when you resize just a little Atom, everything get back to normal ?

**Comment by kjbrum** [comment]
Actually things seem to be working pretty much normal now, it just happens when I initially split the screen.

**Comment by MoOx** [comment]
Yeah spilt doesn't trigger the right resize event. Dup of #113
