### ISSUE TITLE
Request: Open existing term2 tab from keyboard

### ISSUE THREAD

**Issue by labtoast** [webBoxio/atom-term2#146]
Request: A method to get back to a term2 tab without clicking on the tabs in atom.

Lots of open tabs makes navigating with them ineffective so I use keyboard for navigation (usually cmd-t or cmd-b). It would be awesome for a term2 tab to show up with the cmd-b menu but I don't know how to do this right now. A callable function that I could map to a key would be the next best thing. Thanks for the package!

**Comment by MoOx** [comment]
Please subscribe to #6 for this.
