### ISSUE TITLE
Can't not install term2  version 0.9.11 on window 8

### ISSUE THREAD

**Issue by f3wenbo** [webBoxio/atom-term2#149]
I have tried serval times to install term2 on my atom. But it always failed.
Here is the error log. Please check. My os is window 8.1

 pty.js@0.2.7-1 install C:\Users\BW\AppData\Local\Temp\apm-install-dir-11565-9444-1lwor96\node_modules\term2\node_modules\pty.js
> node-gyp rebuild

C:\Users\BW\AppData\Local\Temp\apm-install-dir-11565-9444-1lwor96\node_modules\term2\node_modules\pty.js>node "C:\Users\BW\AppData\Local\atom\app-1.0.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gyp: deps\winpty\winpty.gyp not found (cwd: C:\Users\BW\AppData\Local\Temp\apm-install-dir-11565-9444-1lwor96\node_modules\term2\node_modules\pty.js) while loading dependencies of binding.gyp while trying to load binding.gyp
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\BW\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\BW\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\BW\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\BW\\.atom\\.apmrc" "install" "C:\\Users\\BW\\AppData\\Local\\Temp\\d-11565-9444-1wm4s1j\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by MoOx** [comment]
Dup of #132, see https://github.com/webBoxio/atom-term2/issues/132#issuecomment-117633985
