### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by andreldm** [webBoxio/atom-term2#15]
I've just download the windows build of atom provided by someguy123(Atom Build 0.99.0-ea0773e) and installed term2.
At first, Atom was complaining about VS 2010 or 2012 not installed. So I installed the 2010 version and term2 was installed successfully.
But when I try to open a terminal(via menu, ctrl+shift+p or keystroke) nothing happens.

I'm sorry, but I can't supply any log or debug info. If there's anything else needed to debug this, please let me know.

System: Windows 7 x64 Ultimate

**Comment by MoOx** [comment]
We need first to handle #132, closing this one for now.
