### ISSUE TITLE
Text Wrapping

### ISSUE THREAD

**Issue by Jonjoe** [webBoxio/atom-term2#154]
![http://media.giphy.com/media/xTiTnx93Rpp4w4Gdi0/giphy.gif](http://media.giphy.com/media/xTiTnx93Rpp4w4Gdi0/giphy.gif)

Anyone seen this behaviour before?

**Info**
This is just bash with some autocomplete settings and a custom PS1 with git branch integration. I have removed this and got the same behaviour so i re-added it.

**Comment by MoOx** [comment]
I think I introduced this bug recently. I will take a look when I got some time.

**Comment by guidobouman** [comment]
This usually happens with a faulty PS1. Where some coloring isn't closed properly. You sure you removed it, and properly restarted your terminal session?

**Comment by Jonjoe** [comment]
@guidobouman 100% not environmental. I reformed my macbook yesterday and decided to go atom instead of sublime this time around. The Os is basically pristine. To confirm i did comment out everything in my bash and restarted my comp. 

Same thing happens, if anything its worse lol. 

@MoOx do you accept pull requests? If you pop some info and where you think this originated i can take a look if you don't have time.

**Comment by MoOx** [comment]
PR are always welcome. Not sure where to look, I am a new collaborator (because this plugin was sort of unmaintained until some days ago ^^). Owners are pretty fast to merge/release PRs.

**Comment by audrummer15** [comment]
This is due to a dash in the path name. In my case, the text after the dash jumps back and forth from the top line to the next line. This only happens if the folder name with the dash is the last element of the path. For example, this path jumps:
~/Development/this-project$

This path does not:
~/Development/this-project/nextFolder$

**Comment by lolo85** [comment]
I have the same issue as "audrummer15"
Instead having in a single line: "bash-3.2$", the text after the dash sign jumps back and forth from the top line to the next line: "bash-
                                  3.2$"

**Comment by lolo85** [comment]
If you switch off the option "Cursor Blink" the "Bash line" does NOT jump, but still the terminal does not work correctly. I mean, if you feed terminal with any command with the dash sign, the problems with text wrapping occurs again:

bash-3.2$ ls -al 
ls -
al

bash-3.2$ du -sh
du -
sh

**Comment by Jonjoe** [comment]
Confirmed this is the exact same issue. My behaviour is because i disabled cursor blink. This issue seems to be a wrapping issue. maybe the containers are not full width? @MoOx

**Comment by MoOx** [comment]
I think there is no real container. I think the terminal is made using  whitespace pre + &nbsp;.
PR are welcome, I am busy atm.

**Comment by MoOx** [comment]
Please guys can you try this simple fix ? https://github.com/webBoxio/atom-term2/pull/158

**Comment by Jonjoe** [comment]
@MoOx thats solved the issue. Im going to make a gif and load it in here. This will help people apply the fix if they dont know how to manually edit plugins.

**Comment by Jonjoe** [comment]
Hey all, yup that seems to have fixed it! ^.^
