### ISSUE TITLE
Is there a way to change the default height of the panel?

### ISSUE THREAD

**Issue by typkrft** [webBoxio/atom-term2#156]
I apologize if this isn't the right place for this question. 

When I open a new panel at the bottom it takes up half of the Atom window. I was looking through the source and changed a couple things here and there, but just could not figure out where that Height is set. 

Thanks for the wonderful add-on,
Brandon

**Comment by MoOx** [comment]
This part is actually tricky. We need to compute (line-)height to adjust height in the plugin. What is your use case ?

**Comment by typkrft** [comment]
This may be over my head. I am just trying to make the terminal panel 200 pixels on start.

**Comment by MoOx** [comment]
So you are opening it at the top of your current pane ?
If so it's more an Atom issue.

**Comment by typkrft** [comment]
For instance If I was writing a c file and wanted to run it in a terminal and when I open term2 it takes up half the window. I just assumed there was a setting somewhere I could change. I am just being lazy though resizing it manually is not that difficult. Thanks again for the info!

**Comment by MoOx** [comment]
Yeah so this case is an Atom problem, not one of this plugin :/

**Comment by MoOx** [comment]
You may found others plugins to help about that.
