### ISSUE TITLE
Add settings to support font size 

### ISSUE THREAD

**Issue by wizwjw** [webBoxio/atom-term2#159]
Default font size is too small in atom 1.0.

**Comment by ebonet** [comment]
+1

Small screen with large pixel density, it's hard to read.

**Comment by MoOx** [comment]
It's supposed to be the same as your code. Can you share a screen shot?

**Comment by ebonet** [comment]
Sure

![Screenshot](https://cloud.githubusercontent.com/assets/3444559/8747374/b2485ebc-2c68-11e5-97f8-21b8cd57208d.png)

**Comment by MoOx** [comment]
Oh yeah this looks like a bug...

**Comment by genghisjahn** [comment]
Yeah, I'm seeing the same thing.

![screen shot 2015-07-30 at 5 31 26 pm](https://cloud.githubusercontent.com/assets/921877/8995651/e32cec64-36e0-11e5-9e0a-46534ebf5672.png)

![screen shot 2015-07-30 at 5 31 38 pm](https://cloud.githubusercontent.com/assets/921877/8995655/e95ccbd6-36e0-11e5-8162-880af1db49b2.png)

**Comment by krrg** [comment]
+1 on this, really small on Retina display.

**Comment by genghisjahn** [comment]
Yeah, forgot to mention I'm on a retina screen.

**Comment by travs** [comment]
+1 here, retina screen as well

**Comment by ebonet** [comment]
Not on retina display here.

**Comment by MoOx** [comment]
Can some of you test the proposed line here https://github.com/webBoxio/atom-term2/commit/75c266e8b2680701c16ae9e2ed6dd0c42a2973a9#commitcomment-12635263 ? Thanks.
