### ISSUE TITLE
Font is not monospace on clean install

### ISSUE THREAD

**Issue by voltrevo** [webBoxio/atom-term2#167]
![screen shot 2015-07-29 at 5 06 18 pm](https://cloud.githubusercontent.com/assets/9291586/8951793/32d6c21c-3614-11e5-81a7-14ccf6f01bf7.png)

Also can't figure out how to configure this? But surely it should be some kind of monospace by default anyway?

**Comment by jchamb2010** [comment]
I had this same issue,

Go to settings, click on "Open Config Folder"
Open the file /packages/term2/styles/term2.less
Add the following between lines 7 and line 8, "font-family: monospace;"
![screen shot 2015-08-03 at 3 10 51 pm](https://cloud.githubusercontent.com/assets/153071/9045536/dcd46bc6-39f1-11e5-89d9-9a36eabfcfd9.png)

**Comment by MoOx** [comment]
Currently, this plugin is taking the font-family of your configuration.
Did you use non monospaced font for the code ?

**Comment by MoOx** [comment]
Can you tell us what font are you using in Atom preferences please ?

**Comment by jchamb2010** [comment]
Personally I didn't change any Atom preferences from default, I just installed term2 and it didn't have monospaced font so I fixed it.

**Comment by MoOx** [comment]
Can you check Atom Menu > Preferences > Settings tab > Editor Settings section > Font family and tell me what you have here please ?

**Comment by MoOx** [comment]
Ok I see that I have personally specified a font. I guess defaut value is empty like you said. I removed it and was able to reproduce the issue.
I will be able to fix that easily by getting the user font || monospace.
