### ISSUE TITLE
Certain commands fail from bash

### ISSUE THREAD

**Issue by 25and1** [webBoxio/atom-term2#35]
![image](https://cloud.githubusercontent.com/assets/2343130/3832062/379c101a-1d9a-11e4-8a65-6168375aa4a4.png)

I was trying to launch another atom window from within term2 and came across this fun little message. No idea what else it may effect.

**Comment by brad-jones** [comment]
I have tried the workaround mentioned, however I still cant get atom to fire up from a term2 terminal.
In this example I have atom set as my default git editor and this is the output I get.

![selection_147](https://cloud.githubusercontent.com/assets/2754772/5994380/09beea38-aac5-11e4-95fc-344da0821b37.png)

And if I just try atom directly I get:

![selection_148](https://cloud.githubusercontent.com/assets/2754772/5994387/4956fab4-aac5-11e4-8b52-76d1ebab50c1.png)

Any ideas?

**Comment by MoOx** [comment]
Closing in favor of #50
