### ISSUE TITLE
Add ability to use own font for term2 tabs

### ISSUE THREAD

**Issue by deiga** [webBoxio/atom-term2#43]
I'm using custom symbols in my terminal statusline, and I'd like to tell this package what font to use. 

Or atleast use the same font which the editor uses.

**Comment by adius** [comment]
+1

**Comment by iclanzan** [comment]
Yes, please!

**Comment by Codelica** [comment]
:+1:  Yep..  same as editor would be just fine to start.

**Comment by jsallis** [comment]
:+1: Same font as editor default would be ideal.

**Comment by nwinkler** [comment]
:+1:
