### ISSUE TITLE
[Question] Mac $PATH is not set?

### ISSUE THREAD

**Issue by ericfong** [webBoxio/atom-term2#45]
I am new to this package.

I am using mac. when I open the term2. I found that node, gulp, grunt, and all other npm install -g are missing.

How should I setup my env?

**Comment by DevNaga** [comment]
language ```go``` command didn't work for me either... followed the steps from @soblom , restarted atom and everything is just fine. Thanks!

**Comment by MoOx** [comment]
Closing in favor of #50
