### ISSUE TITLE
Terminal tab still black if started from the terminal (bash)

### ISSUE THREAD

**Issue by F0x06** [webBoxio/atom-term2#46]
I found a temporary fix,
Is to start Atom from the app launcher, then i can get the terminal tab working 

![term](https://cloud.githubusercontent.com/assets/7167311/4028113/784e57a6-2c38-11e4-86bf-b21ac61a6857.png)

Thanks in advance, cheers,
F0x

**Comment by MoOx** [comment]
Still relevant ?
