### ISSUE TITLE
how are ANSII color codes handled?

### ISSUE THREAD

**Issue by loveencounterflow** [webBoxio/atom-term2#53]
when i do 

```bash
echo -e "\x1b[38;05;64mhelo"
```
in my terminal emulator, i get a green colored output; when i do the same from the term2 prompt, the text remains in the default text color. however, when i use `ls` with colors and when i run the `node` REPL, values *are* echoed with colors. 

so what is it that keeps the colors in one case and suppresses them in the other? i tried to write some NodeJS code that uses `console.log` to output colorful text, but that only works in my standard terminal emulator, not in term2.

**Comment by jmendeth** [comment]
There are different types of [escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code) to [change the color](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors).
First is the standard, widely supported one:

    \x1b[3Nm     Changes text color to N. (N is a digit from 0 to 7 selecting the color from the terminal palette)
    \x1b[4Nm     Changes background to N. (N is a digit from 0 to 7 selecting the color from the terminal palette)

This is what most programs (Node, NPM, ls) use, and it works in term2.

But then, there is an *extended* syntax that is not standarized: its implementation depends entirely on the terminal emulator. *Most* terminals support this:

    \x1b[38;5;XXXm    Change text color to XXX. (XXX is a number from 0 to 255)
    \x1b[48;5;XXXm    Change background to XXX. (XXX is a number from 0 to 255)

    \x1b[38;2;RR;GG;BBm    Change text color to RGB-specified color (RR, GG, BB go from 0 to 255)
    \x1b[48;2;RR;GG;BBm    Change background to RGB-specified color (RR, GG, BB go from 0 to 255)

But again, it's not standard, so it's normal that `term.js` doesn't implement it.
I recommend you to stick to the traditional, but limited, syntax for compatibility.

**Comment by MoOx** [comment]
Currently, I get a green text with `echo -e "\x1b[38;05;64mhelo"`. Closing.
