### ISSUE TITLE
Unable to switch back to tab

### ISSUE THREAD

**Issue by jonathanbello** [webBoxio/atom-term2#54]
In Atom, when you have multiple tabs you can press 'alt-tab' and it will switch you from tab to tab. When i navigate to the terminal tab, I am unable to switch back to my editing tabs when pressing 'alt-tab'.

**Comment by hamosapience** [comment]
+1

**Comment by MoOx** [comment]
Dup of #6

**Comment by AnickaBurova** [comment]
I had the same problem, but it looks like, if you press tab after you alt-tab (ctrl-tab) in to term2, term2 will get the focus and you can start using it.
