### ISSUE TITLE
Unable to install Term2 package - neither on windows 7, and niether on Mac OS X (maverick)

### ISSUE THREAD

**Issue by Ajar-Ajar** [webBoxio/atom-term2#62]
Hi, I tried to install via the Settings panel in the editor on windows and got the following errors:
If it doesn't yet work on Windows, say it is Mac Only in the Package description, though it doesn't really work there either... I'll post the mac errors straight after this post.
Any suggestions?

> pty.js@0.2.4 install C:\Users\WINDOW~1\AppData\Local\Temp\apm-install-dir-114926-17888-ccohm3\node_modules\term2\node_modules\pty.js
> node-gyp rebuild

C:\Users\WINDOW~1\AppData\Local\Temp\apm-install-dir-114926-17888-ccohm3\node_modules\term2\node_modules\pty.js>node "e:\Program Files\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

npm http GET https://registry.npmjs.org/debounce/0.0.3
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/atom-term.js/0.0.55
npm http GET https://registry.npmjs.org/keypather
npm http GET https://github.com/chjj/pty.js/archive/master.tar.gz
npm http 200 https://registry.npmjs.org/atom-term.js/0.0.55
npm http GET https://registry.npmjs.org/atom-term.js/-/atom-term.js-0.0.55.tgz
npm http 200 https://registry.npmjs.org/debounce/0.0.3
npm http GET https://registry.npmjs.org/debounce/-/debounce-0.0.3.tgz
npm http 200 https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/fs-plus/-/fs-plus-2.3.1.tgz
npm http 200 https://registry.npmjs.org/atom-term.js/-/atom-term.js-0.0.55.tgz
npm http 200 https://registry.npmjs.org/debounce/-/debounce-0.0.3.tgz
npm http 200 https://registry.npmjs.org/fs-plus/-/fs-plus-2.3.1.tgz
npm http 200 https://registry.npmjs.org/keypather
npm http GET https://registry.npmjs.org/keypather/-/keypather-1.7.5.tgz
npm http 200 https://github.com/chjj/pty.js/archive/master.tar.gz
npm http 200 https://registry.npmjs.org/keypather/-/keypather-1.7.5.tgz
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
npm http 200 https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/extend/-/extend-1.2.1.tgz
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/async/-/async-0.2.10.tgz
npm http 200 https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http GET https://registry.npmjs.org/nan/-/nan-1.0.0.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
npm http 200 https://registry.npmjs.org/extend/-/extend-1.2.1.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.2.10.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-1.0.0.tgz
npm http 200 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.1.tgz
gyp: deps\winpty\winpty.gyp not found (cwd: C:\Users\WINDOW~1\AppData\Local\Temp\apm-install-dir-114926-17888-ccohm3\node_modules\term2\node_modules\pty.js)
gypnpm http 200 https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.1.tgz
npm http GET https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "e:\\Program Files\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "e:\\Program Files\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "e:\\Program Files\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Windows7Pro\\.atom\\.apmrc" "install" "C:\\Users\\WINDOW~1\\AppData\\Local\\Temp\\d-114926-17888-c0n1a2\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\WINDOW~1\AppData\Local\Temp\apm-install-dir-114926-17888-ccohm3
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm

**Comment by joaom182** [comment]
+1 Atom package term2 on Windows 8.1

**Comment by jacereda** [comment]
I got it to compile with this:

https://github.com/jacereda/pty.js/commit/f7cc38c0e5bec836371b760ff5c42e1f503a879e

**Comment by Ajar-Ajar** [comment]
@jacereda - do you mind elaborating?
Got what to compile? on which platform? to what use? how?
Main problem is node-gyp related packages (like term2 but many others) on windows for the most part (but not only) due to the lack of c++ compiler, one has to download & install various mishmash of 1.6 Gigs of dependencies give or take. most people give up windows node development for this reason only and install a VM with Ubuntu just to avoid the nightmare.
I would just conclude the whole of it with 5 lines that nobody knows what to do with and on which platform. I think you can be somewhat more generous with your description.
Cheers
Ajar

**Comment by jacereda** [comment]
@Ajar-Ajar That patch makes pty.js compile with recent Xcode releases. In my case the atom-term2 build went smooth when using the patched pty.js version.

**Comment by Ajar-Ajar** [comment]
Thanks @jacereda, so you are talking about Mac then...
The nightmare is with running node on windows for the most part I guess...

**Comment by MoOx** [comment]
Dup of #44 / #132

**Comment by ardit700** [comment]
No fix yet?

**Comment by echavess** [comment]
Dear all, I am trying to install term2 in atom. I am using Mac OSX el Capitan. I get the next error: 

> pty.js@0.2.13 install /private/var/folders/b9/9g0m9s9j117gnplcgs3mhplr0000gn/T/apm-install-dir-116710-1409-13s6xq9/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../node_modules/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:560:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:566:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:571:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:577:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/src/node_buffer.h:44:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/src/node_buffer.h:56:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/src/node_buffer.h:41:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/src/node_buffer.h:49:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:772:12: error: no viable conversion from returned value of type 'v8::MaybeLocal<v8::Object>' to function return type 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:216:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:216:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:220:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:333:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/src/node.h:34:
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:227:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:186:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:501:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/src/node.h:34:
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:227:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:186:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:511:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/src/node.h:34:
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:227:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:186:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1645:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/src/node.h:34:
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:227:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/ech/.atom/.node-gyp/.node-gyp/0.37.8/deps/v8/include/v8.h:186:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1776:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
14 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/b9/9g0m9s9j117gnplcgs3mhplr0000gn/T/apm-install-dir-116710-1409-13s6xq9/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ech/.atom/.apm/.apmrc" "--userconfig" "/Users/ech/.atom/.apmrc" "install" "/private/var/folders/b9/9g0m9s9j117gnplcgs3mhplr0000gn/T/d-116710-1409-52aiam/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/b9/9g0m9s9j117gnplcgs3mhplr0000gn/T/apm-install-dir-116710-1409-13s6xq9/npm-debug.log

Any ideas how to fix this? 
Thanks!
