### ISSUE TITLE
can't install term2 0.9.4

### ISSUE THREAD

**Issue by nino22** [webBoxio/atom-term2#67]
I can't install term2 on atom 0.145
How to fix it?
i got this error :

> pty.js@0.2.4 install /tmp/apm-install-dir-1141013-5084-11ih3hw/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/tmp/apm-install-dir-1141013-5084-11ih3hw/node_modules/term2/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: Leaving directory `/tmp/apm-install-dir-1141013-5084-11ih3hw/node_modules/term2/node_modules/pty.js/build'

npm http GET https://registry.npmjs.org/atom-term.js/0.0.55
npm http GET https://registry.npmjs.org/debounce/0.0.3
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/keypather
npm http GET https://github.com/chjj/pty.js/archive/master.tar.gz
npm http 304 https://registry.npmjs.org/atom-term.js/0.0.55
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/debounce/0.0.3
npm http 304 https://registry.npmjs.org/keypather
npm http 200 https://github.com/chjj/pty.js/archive/master.tar.gz
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/extend
make: g++: Command not found
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-1141013-5084-11ih3hw/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/bin/node" "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/home/nino/.atom/.apmrc" "install" "/home/nino/.atom/.node-gyp/.atom/.apm/term2/0.9.4/package.tgz" "--target=0.18.0" "--arch=x64"
npm ERR! cwd /tmp/apm-install-dir-1141013-5084-11ih3hw
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm http 304 https://registry.npmjs.org/underscore
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/apm-install-dir-1141013-5084-11ih3hw/npm-debug.log
npm ERR! not ok code 0

**Comment by jamesmarkcook** [comment]
Same here. Any ideas anyone?

**Comment by jparkton** [comment]
Same here

**Comment by MoOx** [comment]
Dup of #44
