### ISSUE TITLE
Enhancement request: Themes

### ISSUE THREAD

**Issue by JikkuJose** [webBoxio/atom-term2#69]
Such a brilliant plugin. I just tried Atom seeing this plugin alone. I always work in terminal alone using tmux and Vim. But the possibility of running that setup in Atom is exciting due to a bunch of things. This plugin effectively just lets me change my environment from Mac Terminal to Atom. Will be writing a blog with the advantages of it.

Anyways, one aspects I found difficult was that to get the look and feel of the environment, I wish I could replicate my terminal environment exactly as I have it in Terminal, it would be great if the plugin could accept Terminal/iTerm2 colour themes. This would make the switch to it perfect.

**Comment by MoOx** [comment]
Some work have been made (background for now). Closing in favor of #121
