### ISSUE TITLE
When using zsh as shell a lot of flickering happens while typing

### ISSUE THREAD

**Issue by sarod** [webBoxio/atom-term2#71]
Term2 works fine with dash/bash however if you use zsh as shell a lot of flickering happens when typing a command.

Sometimes the privous command text overlaps the prompt.

**Comment by imperez** [comment]
I'm getting this exact same issue. A lot of text overlap and flickering of commands. Any update on what could be the cause?

**Comment by MoOx** [comment]
I use zsh and don't have this issue. Is it still relevant ?

**Comment by MoOx** [comment]
Reopen if it is.
