### ISSUE TITLE
term2 as bottom pane affects top pane.

### ISSUE THREAD

**Issue by sbromberger** [webBoxio/atom-term2#72]
Not quite sure how to describe this, but given a normal pane (fig 1), 
![fig 1](https://cloud.githubusercontent.com/assets/941359/5284478/574b6bc2-7ac9-11e4-802e-1cd23cb28335.png)

Selecting "open new terminal in bottom pane" results in some weird layout (fig 2) - notice the status bar in the middle of the terminal, and notice the tabs of the top pane gone. 
![fig 2](https://cloud.githubusercontent.com/assets/941359/5284479/57695880-7ac9-11e4-8e32-6ab84704967d.png)

Clicking in the top pane results in a rearrangement to the expected layout (fig 3).
![fig 3](https://cloud.githubusercontent.com/assets/941359/5284480/5769a9a2-7ac9-11e4-9cd0-90691f5846f5.png)

I have no CSS/LESS overrides, version is 0.9.4 running on Atom 0.152.0.

**Comment by MoOx** [comment]
Seems outdated. Feel free to reopen if you still have the issue.
