### ISSUE TITLE
Install problem in windows

### ISSUE THREAD

**Issue by mark-hahn** [webBoxio/atom-term2#74]
Node-gyp won't build on install on my system ...

    > pty.js@0.2.4 install C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-1141111-29208-1ow6nmg\node_modules\term2\node_modules\
    pty.js
    > node-gyp rebuild

    C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-1141111-29208-1ow6nmg\node_modules\term2\node_modules\pty.js>node "c:\Users\A
    dministrator\AppData\Local\atom\app-0.157.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\bin\node-gyp-bin\
    \..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

    npm http GET https://registry.npmjs.org/atom-term.js/0.0.55
    npm http GET https://registry.npmjs.org/debounce/0.0.3
    npm http GET https://registry.npmjs.org/keypather
    npm http GET https://github.com/chjj/pty.js/archive/master.tar.gz
    npm http GET https://registry.npmjs.org/fs-plus
    npm http 200 https://registry.npmjs.org/atom-term.js/0.0.55
    npm http GET https://registry.npmjs.org/atom-term.js/-/atom-term.js-0.0.55.tgz
    npm http 304 https://registry.npmjs.org/fs-plus
    npm http 200 https://registry.npmjs.org/debounce/0.0.3
    npm http GET https://registry.npmjs.org/debounce/-/debounce-0.0.3.tgz
    npm http 200 https://registry.npmjs.org/keypather
    npm http GET https://registry.npmjs.org/keypather/-/keypather-1.7.5.tgz
    npm http 200 https://registry.npmjs.org/atom-term.js/-/atom-term.js-0.0.55.tgz
    npm http 200 https://registry.npmjs.org/debounce/-/debounce-0.0.3.tgz
    npm http 200 https://registry.npmjs.org/keypather/-/keypather-1.7.5.tgz
    npm http 200 https://github.com/chjj/pty.js/archive/master.tar.gz
    npm http GET https://registry.npmjs.org/extend
    npm http GET https://registry.npmjs.org/underscore-plus
    npm http GET https://registry.npmjs.org/rimraf
    npm http GET https://registry.npmjs.org/mkdirp
    npm http GET https://registry.npmjs.org/async
    npm http GET https://registry.npmjs.org/nan
    npm http 304 https://registry.npmjs.org/rimraf
    npm http 200 https://registry.npmjs.org/extend
    npm http GET https://registry.npmjs.org/extend/-/extend-1.2.1.tgz
    npm http 304 https://registry.npmjs.org/nan
    npm http 200 https://registry.npmjs.org/mkdirp
    npm http 200 https://registry.npmjs.org/extend/-/extend-1.2.1.tgz
    npm http 200 https://registry.npmjs.org/async
    npm http 200 https://registry.npmjs.org/underscore-plus
    npm http GET https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.2.tgz
    gyp: deps\winpty\winpty.gyp not found (cwd: C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-1141111-29208-1ow6nmg\node_module
    s\term2\node_modules\pty.js)
    gypnpm http 200 https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.2.tgz
    npm http GET https://registry.npmjs.org/underscore
    npm http 200 https://registry.npmjs.org/underscore
    npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the pty.js@0.2.4 install script.
    npm ERR! This is most likely a problem with the pty.js package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls pty.js
    npm ERR! There is likely additional logging output above.

    npm ERR! System Windows_NT 6.2.9200
    npm ERR! command "c:\\Users\\Administrator\\AppData\\Local\\atom\\app-0.157.0\\resources\\app\\apm\\node_modules\\atom-package-man
    ager\\bin\\\\node.exe" "c:\\Users\\Administrator\\AppData\\Local\\atom\\app-0.157.0\\resources\\app\\apm\\node_modules\\atom-packa
    ge-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Administrator\\AppData\\Local\\atom\\app-0.157.0\\res
    ources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Administrator\\.atom\\.apmrc" "install" "
    C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\d-1141111-29208-1uu5ea6\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2
    013"
    npm ERR! cwd C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-1141111-29208-1ow6nmg
    npm ERR! node -v v0.10.33
    npm ERR! npm -v 1.4.4
    npm ERR! code ELIFECYCLE
    npm

## Versions

* **Atom:**       0.157.0
* **Atom-Shell:** 0.19.4
* **OS:**         Microsoft Windows 8.1 Pro with Media Center
* **Misc**
    * apm  0.114.0
    * npm  1.4.4
    * node 0.10.33
    * python 2.7.8
    * git 1.7.11.msysgit.1
    * visual studio 2013

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.5.3.</small>

**Comment by joaom182** [comment]
+1

**Comment by Cweili** [comment]
+1

**Comment by alcipir** [comment]
+1

**Comment by divmgl** [comment]
+1

**Comment by denqxotl** [comment]
+1

**Comment by yothinix** [comment]
+1

**Comment by djmittens** [comment]
+1

**Comment by iamstarkov** [comment]
To be honest it’s not directly issue for atom-term2, because it is the problem of pty.js itself: 
chjj/pty.js#85, chjj/pty.js#95, chjj/pty.js#65, chjj/pty.js#54 and chjj/pty.js#45

**Comment by iamstarkov** [comment]
it’s strange that @Azerothian, @abe33 didnt’t tell anything about it in this issue

**Comment by iamstarkov** [comment]
btw for all +1 guys, if you want to help, go forward to suggested pty.js issues

**Comment by iamstarkov** [comment]
or suggest anything else to replace pty.js

**Comment by MoOx** [comment]
Dup of #132

**Comment by madtrapper** [comment]
+1
