### ISSUE TITLE
Can't copy/paste

### ISSUE THREAD

**Issue by kmdavis** [webBoxio/atom-term2#76]
I am unable to copy text inside a terminal tab, and I am unable to paste the contents of my clipboard into a terminal tab.

**Comment by agektmr** [comment]
+1

**Comment by mickael-moreau** [comment]
+1

**Comment by spider-network** [comment]
+1

**Comment by blimmer** [comment]
This would be really great.

**Comment by MoOx** [comment]
Even if it's buggy, it's doable right now. We might improve this later (there is other issues for that)
