### ISSUE TITLE
Term2 0.9.4 won't install

### ISSUE THREAD

**Issue by ldg** [webBoxio/atom-term2#81]
I'm getting this error when installing term2, both from the package manager and apm:
Atom version 0.165.0

> pty.js@0.2.4 install /private/var/folders/by/dyhbhyyn5gnc6gw494pyn1h40000gn/T/apm-install-dir-1141124-14353-hl1pyy/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

npm http GET https://registry.npmjs.org/debounce/0.0.3
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/keypather
npm http GET https://registry.npmjs.org/atom-term.js/0.0.55
npm http GET https://github.com/chjj/pty.js/archive/master.tar.gz
npm http 304 https://registry.npmjs.org/debounce/0.0.3
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/keypather
npm http 304 https://registry.npmjs.org/atom-term.js/0.0.55
npm http 200 https://github.com/chjj/pty.js/archive/master.tar.gz
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/underscore
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/by/dyhbhyyn5gnc6gw494pyn1h40000gn/T/apm-install-dir-1141124-14353-hl1pyy/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/underscore
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.5.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/scottmcintire/.atom/.apmrc" "install" "/Users/scottmcintire/.atom/.node-gyp/.atom/.apm/term2/0.9.4/package.tgz" "--target=0.18.0" "--arch=x64"
npm ERR! cwd /private/var/folders/by/dyhbhyyn5gnc6gw494pyn1h40000gn/T/apm-install-dir-1141124-14353-hl1pyy
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/by/dyhbhyyn5gnc6gw494pyn1h40000gn/T/apm-install-dir-1141124-14353-hl1pyy/npm-debug.log
npm ERR! not ok code 0

**Comment by ecowden** [comment]
+1 -- I'm getting the same issue.

**Comment by EagleDelta2** [comment]
+1 Same issue here

**Comment by SduyXD** [comment]
+1 I Have the same issue with atom "0.165.0"

**Comment by hunterboerner** [comment]
Same

**Comment by kobika** [comment]
same

**Comment by MoOx** [comment]
Dup of #132
