### ISSUE TITLE
Term2 Wont install on OsX 10.10.1

### ISSUE THREAD

**Issue by SduyXD** [webBoxio/atom-term2#82]
///////////////////////////// ERROR START /////////////////////////////////////
> pty.js@0.2.4 install /private/var/folders/7h/2jnjvkhx22gf43y1fbqlfp2w0000gn/T/apm-install-dir-11507-5645-1ixj025/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/atom-term.js/0.0.55
npm http GET https://registry.npmjs.org/debounce/0.0.3
npm http GET https://registry.npmjs.org/keypather
npm http GET https://github.com/chjj/pty.js/archive/master.tar.gz
npm http 304 https://registry.npmjs.org/keypather
npm http 304 https://registry.npmjs.org/debounce/0.0.3
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/atom-term.js/0.0.55
npm http 200 https://github.com/chjj/pty.js/archive/master.tar.gz
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/nan
2015-01-07 01:37:53.598 xcodebuild[5665:121653] [MT] PluginLoading: Required plug-in compatibility UUID C4A681B0-4A26-480E-93EC-1218098B9AA0 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
../src/unix/pty.cc:37:10: fatal error: '/usr/include/util.h' file not found
#include </usr/include/util.h>
         ^
1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/7h/2jnjvkhx22gf43y1fbqlfp2w0000gn/T/apm-install-dir-11507-5645-1ixj025/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.0.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/sduy/.atom/.apmrc" "install" "/Users/sduy/.atom/.node-gyp/.atom/.apm/term2/0.9.4/package.tgz" "--target=0.18.0" "--arch=x64"
npm ERR! cwd /private/var/folders/7h/2jnjvkhx22gf43y1fbqlfp2w0000gn/T/apm-install-dir-11507-5645-1ixj025
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/7h/2jnjvkhx22gf43y1fbqlfp2w0000gn/T/apm-install-dir-11507-5645-1ixj025/npm-debug.log
npm ERR! not ok code 0
///////////////////////////// ERROR END /////////////////////////////////////

my Atom version is 0.165.0

**Comment by mosbrain** [comment]
+1

**Comment by mosbrain** [comment]
Ahh.  It worked after installing it globally.  ```amp install -g term2```

**Comment by eranimo** [comment]
+1

**Comment by SduyXD** [comment]
Install iTerm2(http://iterm2.com), Maybe it can help

**Comment by MoOx** [comment]
Dup of #44
