### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jfefes** [webBoxio/atom-term2#84]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Users/james/Downloads/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/james/.atom/packages/term2/index.coffee:48:11)
```

**Comment by MoOx** [comment]
I guess it has been fixed.
