### ISSUE TITLE
term2 fails on windows 7 pro 64bit

### ISSUE THREAD

**Issue by neuropass** [webBoxio/atom-term2#92]
It fails to install on Win 7 pro 64 bit. 
http://gyazo.com/6783124135a4d1fb8641ee11171616ca.png

Any suggestions?

**Comment by Jonjoe** [comment]
Term wont work with Windows as its a bash terminal (unix). Youll need a Linux distro or OSX.

**Comment by nikswamy** [comment]
Any chance of making this work with cygwin?

**Comment by jshap70** [comment]
I believe that would require atom to be installed under cygwin.  Also I still would doubt the viability of that, as cygwin still uses some core Windows functions.

**Comment by MoOx** [comment]
Dup of #132
