### ISSUE TITLE
Bad keybindings on Linux

### ISSUE THREAD

**Issue by kankaristo** [webBoxio/atom-term2#93]
The current keybindings won't work on most Linux distributions.

```ctrl-alt-arrowkey``` changes between workspaces in most desktop managers, and the keypresses never reach Atom or term2.

On Ubuntu (and possibly other distros), ```ctrl-alt-t``` opens a new terminal window. These keypresses never reach Atom either.

I copied the Mac keybindings, replacing ```cmd``` with ```ctrl```, i.e. ```ctrl-k t arrowkey``` and ```ctrl-k t t```.

Without these, most Linux users can only use term2 through the command palette.

Also, ```ctrl-v``` doesn't work properly. Sometimes it does nothing, sometimes it inserts ```^V``` and pastes twice. ```shift-insert``` is commonly used for pasting in Linux terminals (```ctrl-insert``` is copy), and this seems to work well.

**Comment by sinkingshriek** [comment]
Agreed. And I haven't tried this on other platforms but I can't seem to be able to `copy` either. I usually use `ctrl+shift+c` to copy but it just terminates the shell with `^C`.  I even went ahead and mapped my key as below and it still doesn't work.
```  
'body': 
  'ctrl-alt-y': 'core:copy'
```

**Comment by kankaristo** [comment]
The keybindings (including copy and paste) are fixed in https://github.com/webBoxio/atom-term2/pull/129.
